stages:
  - test

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.uv-cache"

default:
  image: python:3.11-slim
  tags:
    - sce
  before_script:
    - python -V
    - pip install --no-cache-dir uv
    - uv venv
    - . .venv/bin/activate
  cache:
    key: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
    paths:
      - .venv/
      - .uv-cache/

pytest:
  stage: test
  timeout: 360m
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.11"]
        PYTEST_GROUP: [1, 2, 3, 4]
  image: python:${PYTHON_VERSION}-slim
  script:
    - uv sync --extra test
    - |
      if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
      uv pip install pytest-split numba openpyxl pyproj matplotlib
    - uv pip list
    - |
      uv run pytest pandapower/test/shortcircuit/sce_tests/test_sce.py --splits 4 --group ${PYTEST_GROUP}
  rules:
    # Run when a commit is pushed directly to the `sce` branch
    - if: '$CI_COMMIT_BRANCH == "sce"'
      when: always
    # Run when a merge request (any source) targets the `sce` branch
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "sce"'
      when: always
    # Skip the job for all other cases
    - when: never
