stages:
  - test


test:
  before_script:
    - pip install -r requirements.txt
    - python3 --version
    - pip list

  stage: test
  image: python:3.11
  rules:
    - if: '$CI_COMMIT_BRANCH == "sce"'
  script:
    - pytest pandapower/test/shortcircuit/sce_tests/sample_tests