from numpy import dtype

from pandapower._version import __version__, __format_version__
from pandapower.network_schema.tools import get_dtypes
from pandapower.network_schema.bus import schema as bus_schema
from pandapower.network_schema.load import schema as load_schema
from pandapower.network_schema.sgen import schema as sgen_schema
from pandapower.network_schema.switch import schema as switch_schema
from pandapower.network_schema.ext_grid import schema as ext_grid_schema
from pandapower.network_schema.line import schema as line_schema
from pandapower.network_schema.trafo import schema as trafo_schema
from pandapower.network_schema.motor import schema as motor_schema
from pandapower.network_schema.asymmetric_load import schema as asymmetric_load_schema
from pandapower.network_schema.asymmetric_sgen import schema as asymmetric_sgen_schema
from pandapower.network_schema.storage import schema as storage_schema
from pandapower.network_schema.gen import schema as gen_schema
from pandapower.network_schema.shunt import schema as shunt_schema

def get_structure_dict() -> dict:
    """
    This function returns the structure dict of the network
    """
    return {
        # structure data
        "bus": get_dtypes(bus_schema),
        "bus_dc": {  # in methodcall but not parameter docu: geodata, coords
            "name": dtype(str),
            "vn_kv": "f8",
            "type": dtype(str),
            "zone": dtype(str),
            "in_service": "bool",
            "geo": dtype(str),  # missing in docu, not a create method parameter, kwargs?
        },
        "load": get_dtypes(load_schema),
        "sgen": get_dtypes(sgen_schema),
        "motor": get_dtypes(motor_schema),
        "asymmetric_load": get_dtypes(asymmetric_load_schema),
        "asymmetric_sgen": get_dtypes(asymmetric_sgen_schema),
        "storage": get_dtypes(storage_schema),
        "gen": get_dtypes(gen_schema),
        "switch": get_dtypes(switch_schema),
        "shunt": get_dtypes(shunt_schema),
        "svc": {
            "name": dtype(str),
            "bus": "i8",
            "x_l_ohm": "f8",
            "x_cvar_ohm": "f8",
            "set_vm_pu": "f8",
            "thyristor_firing_angle_degree": "f8",
            "controllable": "bool",
            "in_service": "bool",
            "min_angle_degree": "f8",
            "max_angle_degree": "f8",
        },
        "ssc": {
            "name": dtype(str),
            "bus": "i8",
            "r_ohm": "f8",
            "x_ohm": "f8",
            "set_vm_pu": "f8",
            "vm_internal_pu": "f8",
            "va_internal_degree": "f8",
            "controllable": "bool",
            "in_service": "bool",
        },
        "vsc": {
            "name": dtype(str),
            "bus": "i8",
            "bus_dc": "i8",
            "r_ohm": "f8",
            "x_ohm": "f8",
            "r_dc_ohm": "f8",
            "pl_dc_mw": "f8",
            "control_mode_ac": dtype(str),
            "control_value_ac": "f8",
            "control_mode_dc": dtype(str),
            "control_value_dc": "f8",
            "controllable": "bool",
            "in_service": "bool",
            "ref_bus": "u4",  # missing in docu
        },
        "ext_grid": get_dtypes(ext_grid_schema),
        "line": get_dtypes(line_schema),
        "line_dc": {  # in methodcall but not parameter docu: geodata, alpha, temperature_degree_celsius
            "name": dtype(str),
            "std_type": dtype(str),
            "from_bus_dc": "i8",
            "to_bus_dc": "i8",
            "length_km": "f8",
            "r_ohm_per_km": "f8",
            "g_us_per_km": "f8",
            "max_i_ka": "f8",
            "parallel": "i8",
            "df": "f8",
            "type": dtype(str),  # docu broken
            "max_loading_percent": "f8",
            "in_service": "bool",
            "geo": dtype(str),  # missing in docu
        },
        "trafo": get_dtypes(trafo_schema),
        "trafo3w": {  # in methodcall but not parameter docu: vector_group, vkr0_x, vk0_x, max_loading_percent, ahhh warum gibt es 2 create methoden???
            "name": dtype(str),
            "std_type": dtype(str),
            "hv_bus": "i8",
            "mv_bus": "i8",
            "lv_bus": "i8",
            "vn_hv_kv": "f8",
            "vn_mv_kv": "f8",
            "vn_lv_kv": "f8",
            "sn_hv_mva": "f8",
            "sn_mv_mva": "f8",
            "sn_lv_mva": "f8",
            "vk_hv_percent": "f8",
            "vk_mv_percent": "f8",
            "vk_lv_percent": "f8",
            "vkr_hv_percent": "f8",
            "vkr_mv_percent": "f8",
            "vkr_lv_percent": "f8",
            "pfe_kw": "f8",
            "i0_percent": "f8",
            "shift_mv_degree": "f8",
            "shift_lv_degree": "f8",
            "tap_side": dtype(str),
            "tap_neutral": "i8",
            "tap_min": "i8",
            "tap_max": "i8",
            "tap_step_percent": "f8",
            "tap_step_degree": "f8",
            "tap_at_star_point": "bool",
            "tap_pos": "f8",
            "tap_changer_type": dtype(str),
            "tap_dependency_table": "bool",
            "id_characteristic_table": "i8",
            "in_service": "bool",
        },
        "impedance": {
            "name": dtype(str),
            "from_bus": "i8",
            "to_bus": "i8",
            "rft_pu": "f8",
            "xft_pu": "f8",
            "rtf_pu": "f8",
            "xtf_pu": "f8",
            "rft0_pu": "f8",
            "xft0_pu": "f8",
            "rtf0_pu": "f8",
            "xtf0_pu": "f8",
            "gf_pu": "f8",
            "bf_pu": "f8",
            "gt_pu": "f8",
            "bt_pu": "f8",
            "gf0_pu": "f8",
            "bf0_pu": "f8",
            "gt0_pu": "f8",
            "bt0_pu": "f8",
            "sn_mva": "f8",
            "in_service": "bool",
        },
        "tcsc": {
            "name": dtype(str),
            "from_bus": "i8",
            "to_bus": "i8",
            "x_l_ohm": "f8",
            "x_cvar_ohm": "f8",
            "set_p_to_mw": "f8",
            "thyristor_firing_angle_degree": "f8",
            "controllable": "bool",
            "in_service": "bool",
            "min_angle_degree": "f8",
            "max_angle_degree": "f8",
        },
        "dcline": {
            "name": dtype(str),
            "from_bus": "i8",
            "to_bus": "i8",
            "p_mw": "f8",
            "loss_percent": "f8",
            "loss_mw": "f8",
            "vm_from_pu": "f8",
            "vm_to_pu": "f8",
            "max_p_mw": "f8",  # no min_p_mw ?
            "min_q_from_mvar": "f8",
            "max_q_from_mvar": "f8",
            "min_q_to_mvar": "f8",
            "max_q_to_mvar": "f8",
            "in_service": "bool",
        },
        "ward": {
            "name": dtype(str),
            "bus": "i8",
            "ps_mw": "f8",
            "qs_mvar": "f8",
            "pz_mw": "f8",
            "qz_mvar": "f8",
            "in_service": "bool",
        },
        "xward": {
            "name": dtype(str),
            "bus": "i8",
            "ps_mw": "f8",
            "qs_mvar": "f8",
            "pz_mw": "f8",
            "qz_mvar": "f8",
            "r_ohm": "f8",
            "x_ohm": "f8",
            "vm_pu": "f8",
            "slack_weight": "f8",
            "in_service": "bool",  # missing in docu
        },
        "measurement": {
            "name": dtype(str),
            "measurement_type": dtype(str),  # missing in docu
            "element_type": dtype(str),
            "value": "f8",
            "std_dev": "f8",
            "bus": "i8",
            "element": "i8",
            "check_existing": "bool",
            "index": "i8",
            "side": dtype(str),  # missing in docu
        },
        "pwl_cost": {  # not a datastructure or element?
            "power_type": dtype(object),
            "element": "u4",
            "et": dtype(object),
            "points": dtype(object),
        },
        "poly_cost": {  # not a datastructure or element?
            "element": "u4",
            "et": dtype(object),
            "cp0_eur": "f8",
            "cp1_eur_per_mw": "f8",
            "cp2_eur_per_mw2": "f8",
            "cq0_eur": "f8",
            "cq1_eur_per_mvar": "f8",
            "cq2_eur_per_mvar2": "f8",
        },
        "controller": {  # not a datastructure or element?
            "object": dtype(object),
            "in_service": "bool",
            "order": "float64",
            "level": dtype(object),
            "initial_run": "bool",
            "recycle": dtype(object),
        },
        "group": {  # not a datastructure or element?
            "name": dtype(object),
            "element_type": dtype(object),
            "element_index": dtype(object),
            "reference_column": dtype(object),
        },
        "source_dc": {  # docu hat sehr viele fehler...
            "name": dtype(str),
            "type": dtype(str),
            "bus_dc": "i8",  # not the same name in docu
            "p_mw": "f8",
            "scaling": "f8",  # not in create method
            "vm_pu": "f8",  # missing in docu
            "in_service": "bool",
        },
        "load_dc": {
            "name": dtype(str),
            "bus_dc": "i8",
            "p_dc_mw": "f8",
            "scaling": "f8",
            "in_service": "bool",
            "type": dtype(str),
            "controllable": "bool",
        },
        "b2b_vsc": {
            "name": dtype(str),
            "bus": "i8",
            "bus_dc_plus": "i8",
            "bus_dc_minus": "i8",
            "r_ohm": "f8",
            "x_ohm": "f8",
            "r_dc_ohm": "f8",
            "pl_dc_mw": "f8",
            "control_mode_ac": dtype(str),
            "control_value_ac": "f8",
            "control_mode_dc": dtype(str),
            "control_value_dc": "f8",
            "controllable": "bool",
            "in_service": "bool",
        },
        "_empty_res_b2b_vsc": {
            "p_mw": "f8",
            "q_mvar": "f8",
            "p_dc_mw_p": "f8",
            "p_dc_mw_m": "f8",
            "vm_internal_pu": "f8",
            "vm_internal_degree": "f8",
            "vm_pu": "f8",
            "va_degree": "f8",
            "vm_internal_dc_pu_p": "f8",
            "vm_internal_dc_pu_m": "f8",
            "vm_dc_pu_p": "f8",
            "vm_dc_pu_m": "f8",
        },
        "bi_vsc": {  # where is the documentation?
            "name": dtype(object),
            "bus": "u4",
            "bus_dc_plus": "u4",
            "bus_dc_minus": "u4",
            "r_ohm": "f8",
            "x_ohm": "f8",
            "r_dc_ohm": "f8",
            "pl_dc_mw": "f8",
            "control_mode_ac": dtype(object),
            "control_value_ac": "f8",
            "control_mode_dc": dtype(object),
            "control_value_dc": "f8",
            "controllable": "bool",
            "in_service": "bool",
        },
        "_empty_res_bi_vsc": {
            "p_mw": "f8",
            "q_mvar": "f8",
            "p_dc_mw_p": "f8",
            "p_dc_mw_m": "f8",
            "vm_internal_pu": "f8",
            "vm_internal_degree": "f8",
            "vm_pu": "f8",
            "va_degree": "f8",
            "vm_internal_dc_pu_p": "f8",
            "vm_internal_dc_pu_m": "f8",
            "vm_dc_pu_p": "f8",
            "vm_dc_pu_m": "f8",
        },
        # result tables
        "_empty_res_bus": {
            "vm_pu": "f8",
            "va_degree": "f8",
            "p_mw": "f8",
            "q_mvar": "f8"},
        "_empty_res_bus_dc": {
            "vm_pu": "f8",
            "p_mw": "f8"},
        "_empty_res_ext_grid": {
            "p_mw": "f8",
            "q_mvar": "f8"},
        "_empty_res_line": {
            "p_from_mw": "f8",
            "q_from_mvar": "f8",
            "p_to_mw": "f8",
            "q_to_mvar": "f8",
            "pl_mw": "f8",
            "ql_mvar": "f8",
            "i_from_ka": "f8",
            "i_to_ka": "f8",
            "i_ka": "f8",
            "vm_from_pu": "f8",
            "va_from_degree": "f8",
            "vm_to_pu": "f8",
            "va_to_degree": "f8",
            "loading_percent": "f8",
        },
        "_empty_res_line_dc": {
            "p_from_mw": "f8",
            "p_to_mw": "f8",
            "pl_mw": "f8",
            "i_from_ka": "f8",
            "i_to_ka": "f8",
            "i_ka": "f8",
            "vm_from_pu": "f8",
            "vm_to_pu": "f8",
            "loading_percent": "f8",
        },
        "_empty_res_trafo": {
            "p_hv_mw": "f8",
            "q_hv_mvar": "f8",
            "p_lv_mw": "f8",
            "q_lv_mvar": "f8",
            "pl_mw": "f8",
            "ql_mvar": "f8",
            "i_hv_ka": "f8",
            "i_lv_ka": "f8",
            "vm_hv_pu": "f8",
            "va_hv_degree": "f8",
            "vm_lv_pu": "f8",
            "va_lv_degree": "f8",
            "loading_percent": "f8",
        },
        "_empty_res_load": {
            "p_mw": "f8",
            "q_mvar": "f8"
        },
        "_empty_res_asymmetric_load": {
            "p_mw": "f8",
            "q_mvar": "f8"
        },
        "_empty_res_asymmetric_sgen": {
            "p_mw": "f8",
            "q_mvar": "f8"
        },
        "_empty_res_motor": {
            "p_mw": "f8",
            "q_mvar": "f8"
        },
        "_empty_res_sgen": {
            "p_mw": "f8",
            "q_mvar": "f8"
        },
        "_empty_res_shunt": {
            "p_mw": "f8",
            "q_mvar": "f8",
            "vm_pu": "f8"
        },
        "_empty_res_svc": {
            "thyristor_firing_angle_degree": "f8",
            "x_ohm": "f8",
            "q_mvar": "f8",
            "vm_pu": "f8",
            "va_degree": "f8",
        },
        "_empty_res_ssc": {
            "q_mvar": "f8",
            "vm_internal_pu": "f8",
            "va_internal_degree": "f8",
            "vm_pu": "f8",
            "va_degree": "f8",
        },
        "_empty_res_vsc": {
            "p_mw": "f8",
            "q_mvar": "f8",
            "p_dc_mw": "f8",
            "vm_internal_pu": "f8",
            "va_internal_degree": "f8",
            "vm_pu": "f8",
            "va_degree": "f8",
            "vm_internal_dc_pu": "f8",
            "vm_dc_pu": "f8",
        },
        "_empty_res_switch": {
            "i_ka": "f8",
            "loading_percent": "f8",
            "p_from_mw": "f8",
            "q_from_mvar": "f8",
            "p_to_mw": "f8",
            "q_to_mvar": "f8",
        },
        "_empty_res_impedance": {
            "p_from_mw": "f8",
            "q_from_mvar": "f8",
            "p_to_mw": "f8",
            "q_to_mvar": "f8",
            "pl_mw": "f8",
            "ql_mvar": "f8",
            "i_from_ka": "f8",
            "i_to_ka": "f8",
        },
        "_empty_res_tcsc": {
            "thyristor_firing_angle_degree": "f8",
            "x_ohm": "f8",
            "p_from_mw": "f8",
            "q_from_mvar": "f8",
            "p_to_mw": "f8",
            "q_to_mvar": "f8",
            "pl_mw": "f8",
            "ql_mvar": "f8",
            "i_ka": "f8",
            "vm_from_pu": "f8",
            "va_from_degree": "f8",
            "vm_to_pu": "f8",
            "va_to_degree": "f8",
        },
        "_empty_res_dcline": {
            "p_from_mw": "f8",
            "q_from_mvar": "f8",
            "p_to_mw": "f8",
            "q_to_mvar": "f8",
            "pl_mw": "f8",
            "vm_from_pu": "f8",
            "va_from_degree": "f8",
            "vm_to_pu": "f8",
            "va_to_degree": "f8",
        },
        "_empty_res_source_dc": {
            "p_dc_mw": "f8"
        },
        "_empty_res_load_dc": {
            "p_dc_mw": "f8"
        },
        "_empty_res_ward": {
            "p_mw": "f8",
            "q_mvar": "f8",
            "vm_pu": "f8"
        },
        "_empty_res_xward": {
            "p_mw": "f8",
            "q_mvar": "f8",
            "vm_pu": "f8",
            "va_internal_degree": "f8",
            "vm_internal_pu": "f8",
        },
        "_empty_res_trafo_3ph": {
            "p_a_hv_mw": "f8",
            "q_a_hv_mvar": "f8",
            "p_b_hv_mw": "f8",
            "q_b_hv_mvar": "f8",
            "p_c_hv_mw": "f8",
            "q_c_hv_mvar": "f8",
            "p_a_lv_mw": "f8",
            "q_a_lv_mvar": "f8",
            "p_b_lv_mw": "f8",
            "q_b_lv_mvar": "f8",
            "p_c_lv_mw": "f8",
            "q_c_lv_mvar": "f8",
            "pl_a_mw": "f8",
            "ql_a_mvar": "f8",
            "pl_b_mw": "f8",
            "ql_b_mvar": "f8",
            "pl_c_mw": "f8",
            "ql_c_mvar": "f8",
            "i_a_hv_ka": "f8",
            "i_a_lv_ka": "f8",
            "i_b_hv_ka": "f8",
            "i_b_lv_ka": "f8",
            "i_c_hv_ka": "f8",
            "i_c_lv_ka": "f8",
            "loading_a_percent": "f8",
            "loading_b_percent": "f8",
            "loading_c_percent": "f8",
            "loading_percent": "f8",
        },
        "_empty_res_trafo3w": {
            "p_hv_mw": "f8",
            "q_hv_mvar": "f8",
            "p_mv_mw": "f8",
            "q_mv_mvar": "f8",
            "p_lv_mw": "f8",
            "q_lv_mvar": "f8",
            "pl_mw": "f8",
            "ql_mvar": "f8",
            "i_hv_ka": "f8",
            "i_mv_ka": "f8",
            "i_lv_ka": "f8",
            "vm_hv_pu": "f8",
            "va_hv_degree": "f8",
            "vm_mv_pu": "f8",
            "va_mv_degree": "f8",
            "vm_lv_pu": "f8",
            "va_lv_degree": "f8",
            "va_internal_degree": "f8",
            "vm_internal_pu": "f8",
            "loading_percent": "f8",
        },
        "_empty_res_bus_3ph": {
            "vm_a_pu": "f8",
            "va_a_degree": "f8",
            "vm_b_pu": "f8",
            "va_b_degree": "f8",
            "vm_c_pu": "f8",
            "va_c_degree": "f8",
            "p_a_mw": "f8",
            "q_a_mvar": "f8",
            "p_b_mw": "f8",
            "q_b_mvar": "f8",
            "p_c_mw": "f8",
            "q_c_mvar": "f8",
        },
        "_empty_res_ext_grid_3ph": {
            "p_a_mw": "f8",
            "q_a_mvar": "f8",
            "p_b_mw": "f8",
            "q_b_mvar": "f8",
            "p_c_mw": "f8",
            "q_c_mvar": "f8",
        },
        "_empty_res_line_3ph": {
            "p_a_from_mw": "f8",
            "q_a_from_mvar": "f8",
            "p_b_from_mw": "f8",
            "q_b_from_mvar": "f8",
            "p_c_from_mw": "f8",
            "q_c_from_mvar": "f8",
            "p_a_to_mw": "f8",
            "q_a_to_mvar": "f8",
            "p_b_to_mw": "f8",
            "q_b_to_mvar": "f8",
            "p_c_to_mw": "f8",
            "q_c_to_mvar": "f8",
            "pl_a_mw": "f8",
            "ql_a_mvar": "f8",
            "pl_b_mw": "f8",
            "ql_b_mvar": "f8",
            "pl_c_mw": "f8",
            "ql_c_mvar": "f8",
            "i_a_from_ka": "f8",
            "i_a_to_ka": "f8",
            "i_b_from_ka": "f8",
            "i_b_to_ka": "f8",
            "i_c_from_ka": "f8",
            "i_c_to_ka": "f8",
            "i_a_ka": "f8",
            "i_b_ka": "f8",
            "i_c_ka": "f8",
            "i_n_from_ka": "f8",
            "i_n_to_ka": "f8",
            "i_n_ka": "f8",
            "loading_a_percent": "f8",
            "loading_b_percent": "f8",
            "loading_c_percent": "f8",
        },
        "_empty_res_asymmetric_load_3ph": {
            "p_a_mw": "f8",
            "q_a_mvar": "f8",
            "p_b_mw": "f8",
            "q_b_mvar": "f8",
            "p_c_mw": "f8",
            "q_c_mvar": "f8",
        },
        "_empty_res_asymmetric_sgen_3ph": {
            "p_a_mw": "f8",
            "q_a_mvar": "f8",
            "p_b_mw": "f8",
            "q_b_mvar": "f8",
            "p_c_mw": "f8",
            "q_c_mvar": "f8",
        },
        "_empty_res_storage": {
            "p_mw": "f8",
            "q_mvar": "f8"
        },
        "_empty_res_storage_3ph": {
            "p_a_mw": "f8",
            "p_b_mw": "f8",
            "p_c_mw": "f8",
            "q_a_mvar": "f8",
            "q_b_mvar": "f8",
            "q_c_mvar": "f8",
        },
        "_empty_res_gen": {
            "p_mw": "f8",
            "q_mvar": "f8",
            "va_degree": "f8",
            "vm_pu": "f8",
        },
        "_empty_res_protection": {
            "switch_id": "f8",
            "prot_type": dtype(object),
            "trip_melt": "bool",
            "act_param": dtype(object),
            "act_param_val": "f8",
            "trip_melt_time_s": "f8",
        },
        # internal
        "_ppc": None,
        "_ppc0": None,
        "_ppc1": None,
        "_ppc2": None,
        "_is_elements": None,
        "_pd2ppc_lookups": [
            {
                "bus": None,
                "bus_dc": None,
                "ext_grid": None,
                "gen": None,
                "branch": None,
                "branch_dc": None,
            }
        ],
        "version": __version__,
        "format_version": __format_version__,
        "converged": False,
        "OPF_converged": False,
        "name": "",
        "f_hz": 50.0,
        "sn_mva": 1,
    }


def get_std_type_structure_dict() -> dict:
    """
    This function returns the structure dict of the std_types
    """
    return {
        # structure data
        "line": {
            "r_ohm_per_km": "f8",
            "r0_ohm_per_km": "f8",
            "x_ohm_per_km": "f8",
            "x0_ohm_per_km": "f8",
            "c_nf_per_km": "f8",
            "c0_nf_per_km": "f8",
            "g_us_per_km": "f8",
            "g0_us_per_km": "f8",
            "max_i_ka": "f8",
            "type": dtype(object),
            "q_mm2": "f8",
            "alpha": "f8",
            "voltage_rating": dtype(object),
        },
        "line_dc": {
            "r_ohm_per_km": "f8",
            "r0_ohm_per_km": "f8",
            "g_us_per_km": "f8",
            "g0_us_per_km": "f8",
            "max_i_ka": "f8",
            "type": dtype(object),
            "q_mm2": "f8",
            "alpha": "f8",
            "voltage_rating": "f8",
        },
        "trafo": {
            "sn_mva": "f8",
            "vn_hv_kv": "f8",
            "vn_lv_kv": "f8",
            "vk_percnet": "f8",
            "vk0_percent": "f8",
            "vkr_percent": "f8",
            "vkr0_percent": "f8",
            "pfe_kw": "f8",
            "i0_percent": "f8",
            "shift_degree": "f8",
            "vector_group": dtype(object),
            "tap_side": dtype(object),
            "tap_neutral": "f8",
            "tap_min": "f8",
            "tap_max": "f8",
            "tap_step_degree": "f8",
            "tap_step_percent": "f8",
            "tap_change_type": dtype(object),
            "trafo_characteristic_table": "bool",
        },
        "trafo3w": {
            "sn_hv_mva": "f8",
            "sn_mv_mva": "f8",
            "sn_lv_mva": "f8",
            "vn_hv_kv": "f8",
            "vn_mv_kv": "f8",
            "vn_lv_kv": "f8",
            "vk_hv_percent": "f8",
            "vk_mv_percent": "f8",
            "vk_lv_percent": "f8",
            "vk0_hv_percent": "f8",
            "vk0_mv_percent": "f8",
            "vk0_lv_percent": "f8",
            "vkr_hv_percent": "f8",
            "vkr_mv_percent": "f8",
            "vkr_lv_percent": "f8",
            "vkr0_hv_percent": "f8",
            "vkr0_mv_percent": "f8",
            "vkr0_lv_percent": "f8",
            "pfe_kw": "f8",
            "i0_percent": "f8",
            "shift_mv_degree": "f8",
            "shift_lv_degree": "f8",
            "tap_side": dtype(object),
            "tap_neutral": "f8",
            "tap_min": "f8",
            "tap_max": "f8",
            "tap_step_percent": "f8",
            "tap_step_degree": "f8",
            "tap_pos": "f8",
            "tap_at_star_point": "bool",
            "tap_changer_type": dtype(object),
            "id_characteristic_table": "bool",
            "vector_group": dtype(object),
        },
        "fuse": {
            "fuse_type": dtype(object),
            "i_rated_a": "f8",
            "t_avg": dtype(object),
            "t_min": dtype(object),
            "t_total": dtype(object),
            "x_avg": dtype(object),
            "x_min": dtype(object),
            "x_total": dtype(object),
        },
    }
