import pandera.pandas as pa

schema = pa.DataFrameSchema(  # in methodcall but not parameter docu: xn_ohm, pt_percent
    {
        "name": pa.Column(str),
        "std_type": pa.Column(str),
        "hv_bus": pa.Column(int, pa.Check.ge(0)),
        "lv_bus": pa.Column(int, pa.Check.ge(0)),
        "sn_mva": pa.Column(float),
        "vn_hv_kv": pa.Column(float),
        "vn_lv_kv": pa.Column(float),
        "vk_percent": pa.Column(float),
        "vkr_percent": pa.Column(float),
        "pfe_kw": pa.Column(float),
        "i0_percent": pa.Column(float),
        "vk0_percent": pa.Column(float, required=False),
        "vkr0_percent": pa.Column(float, required=False),
        "mag0_percent": pa.Column(float, required=False),
        "mag0_rx": pa.Column(float, required=False),
        "si0_hv_partial": pa.Column(float, required=False),
        "vector_group": pa.Column(str, required=False),
        "shift_degree": pa.Column(float),
        "tap_side": pa.Column(str),
        "tap_neutral": pa.Column(int),
        "tap_min": pa.Column(int),
        "tap_max": pa.Column(int),
        "tap_step_percent": pa.Column(float),
        "tap_step_degree": pa.Column(float, nullable=True),
        "tap_pos": pa.Column(int),
        "tap_changer_type": pa.Column(str),
        "tap_dependency_table": pa.Column(bool, required=False),
        "id_characteristic_table": pa.Column(int, required=False),
        "max_loading_percent": pa.Column(int, required=False),
        "parallel": pa.Column(int, pa.Check.ge(0)),
        "df": pa.Column(float),
        "in_service": pa.Column(bool),
        "oltc": pa.Column(bool, required=False),
        "power_station_unit": pa.Column(bool, required=False),  # not in create method call
        "tap2_side": pa.Column(int, required=False),
        "tap2_neutral": pa.Column(int, required=False),
        "tap2_min": pa.Column(int, required=False),
        "tap2_max": pa.Column(int, required=False),
        "tap2_step_percent": pa.Column(float, required=False),
        "tap2_step_degree": pa.Column(float, required=False),
        "tap2_pos": pa.Column(int, required=False),
        "tap2_changer_type": pa.Column(float, required=False),
        "leakage_resistance_ratio_hv": pa.Column(float, required=False),  # not in create method call
        "leakage_reactance_ratio_hv": pa.Column(float, required=False),  # not in create method call
    },
    strict=False,
)
