name: pr-sync-tutorials.yml
on:
  pull_request:
    types: [ synchronize ]
    paths:
      - pandapower/network_schema/**

permissions:
  contents: read

jobs:
  network_schema:
    # This tests only the network_schema tests due to the large amount these are only tested on min/max python version
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        #python-version: ['3.11', '3.14']
        # Reminder: when removing the support of an old python version here, then don't forget to
        # remove it also in pyproject.toml 'requires-python' and the release pipelines
        group: [ 1, 2, 3, 4 ]
    steps:
#      - uses: julia-actions/setup-julia # Update version when using this by adding commit sha!
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          #python-version: ${{ matrix.python-version }}
          python-version: '3.14'
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Install dependencies
        run: |
          uv sync --extra all --extra test --extra pandamodels --extra pgm
          uv pip uninstall juliacall
          uv pip install pytest-cov pytest-split
      - name: List of installed packages
        run: |
          uv pip list
      - name: Test with pytest, Codecov and Coverage
        run: |
          uv run pytest --cov=./ --cov-report=xml --splits 4 --group ${{ matrix.group }} pandapower/test/network_schema
          cp ./coverage.xml ./coverage-net-schema-${{ matrix.group }}.xml
      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v7
        with:
          name: coverage-net-schema-${{ matrix.group }}
          path: ./coverage-net-schema-${{ matrix.group }}.xml
